### ISSUE TITLE
Importing SPI and not sure how to access "SPEI"

### ISSUE THREAD

**Issue by molofishy** [e-baumer/standard_precip#1]
`from spi import SPI` does not work for me. I think it should rather be:
```
from standard_precip import spi
SPI = spi.SPI()
```

Also, it might be worth mentioning how SPEI should work. The output of `dir(spi)` is:
`['BaseStandardIndex', 'SPI', '__builtins__', '__doc__', '__file__', '__name__', '__package__']`

I.e., there is no "SPEI". 

Thanks,
Oliver

**Comment by e-baumer** [comment]
Apologies for the delay. This issue should be fixed now.
