### ISSUE TITLE
SPI calculation different to R and NCL

### ISSUE THREAD

**Issue by oliverangelil** [e-baumer/standard_precip#2]
I cannot reproduce SPI results I am getting with R or NCL. I've applied SPI on the rainfall data in this git repo ('rainfall_test2.csv') and ensured the R and NCL codes use max-likelihood as is done in this git repo. Also I've made all 3 languages use a window of 10 months (using the rectangular/boxcar smoothing which weights each sample in the window equally), and fit a gamma distribution.

See a figure of the resulting SPI calculations [here](https://drive.google.com/file/d/0BwKa7U-Pu5VMUldGX2RJWlo4Uk0/view?usp=sharing).
The Python, R, and NCL codes are below.

**Python:**
```
from standard_precip import spi
SPI = spi.SPI()
import numpy as np


rainfall_data = np.genfromtxt('rainfall_test2.csv', delimiter=',')
SPI.set_rolling_window_params(span=10, window_type='boxcar', center=False)
SPI.set_distribution_params(dist_type='gamma')
result = SPI.calculate(rainfall_data, starting_month=1)
print result[-10:] .T # print last 10 values
```

The last 10 values here are: 1.18799749,  1.553959  ,  1.50308393,  1.34851829,  1.55083677, 1.75478592,  1.68813806,  1.55901284,  1.05660025,  3.06966442

**R:**

```
library("lmomco")
library("SPEI")

dat = read.csv("rainfall_test2.csv", header = FALSE)
result = spi(dat, scale=10, distribution='Gamma', fit='max-lik', kernel = list(type='rectangular', shift=0))
print(tail(result$fitted, 10)) #print last 10 values

```
The last 10 values here are: 1.22413246  1.51489351  1.44305272  1.41468160  1.72507352  1.67187020 1.83455935  1.53496329  0.76220079 -0.09562831

**NCL:**
```
z1 = asciiread("rainfall_test2.csv",-1,"float")
spi = dim_spi_n(z1,10, False, 0)
```
The last 10 values here are: 1.317463  1.635575  1.550059  1.511726  1.872693  1.81203 
 1.995494  1.660357  0.8005837 -0.1014399; which is similar to R

**Comment by iameztoy** [comment]
Hello Oliver, 

Did you figure it out why was the issue happening? In the case of R, are you using the L-moments (lmomco library) or just conventional moments? The graph derived from python presents higher anomalies that might be affected by outliers, while if you're using the L-mom approach, final results might be less affected. Just wondering,...

In addition to this, I've just slightly modified the code and entered the span as a variable, so I can play around quick with different values. But after calculating different SPI-n the graph and the values I get are always the same. Cannot figure it out why.

Thanks for sharing the code btw! @e-baumer

**Comment by oliverangelil** [comment]
Hey @iameztoy 

No I didn't. The lmomco package is required by the SPEI package, that's why it's loaded as in the example above. So I assume R is using L-moments. Hopefully @e-baumer will help out since he wrote the original code.

Have you been able to at least reproduce my "incorrect" SPI results with python? e.g. the last 10 values starting with 1.18799749.

**Comment by e-baumer** [comment]
47e0e865c68e886aee805932350cd303ed7f2ddb

**Comment by oliverangelil** [comment]
@e-baumer nice work! I haven't tested it out yet, but I trust you when you say results are the samme as R & NCL.

**Comment by Jahangirali09** [comment]
Hi Everyone,

Is it possible you can share code for SPI calculation using gridded data set., e.g. using a NetCDF file as an input.
Thank you.
