### ISSUE TITLE
Integration with Pandas Dataframes

### ISSUE THREAD

**Issue by e-baumer** [e-baumer/standard_precip#3]
@oliverangelil  Is it worthwhile allowing for input data in the form of Pandas Dataframes and outputting data as Pandas Dataframes?

**Comment by oliverangelil** [comment]
@e-baumer, I'm not sure. I usually work with numpy arrays... And it is straightforward to convert a pandas dataframe into a numpy array with `frame.values`, so I don't see much benefit in allowing pandas dataframes to pass into the function...

**Comment by e-baumer** [comment]
New version 1.0
