### ISSUE TITLE
Zeroes gives an "-inf" value.

### ISSUE THREAD

**Issue by wsor330** [e-baumer/standard_precip#8]
The docs include a way to calculate SPI for zeroes but was it not implemented in this package?
Zeros gives an "-inf" value for SPI calculation

**Comment by e-baumer** [comment]
@wsor330 Are you referring to the paper by Lloyd-Hughes and Saunders? I don't believe they specify a way to handle zeros.

**Comment by e-baumer** [comment]
This issue is fixed with the new version 1.0
