### ISSUE TITLE
add in daily SPI calculation?

### ISSUE THREAD

**Issue by wsor330** [e-baumer/standard_precip#9]

**Comment by e-baumer** [comment]
If you are looking for a daily index I would consider either the Effective Drought Index (EDI) or the Keetch-Byram Drought Index (KBDI). You can find information in the following papers:

- https://journals.ametsoc.org/view/journals/clim/12/9/1520-0442_1999_012_2747_oqodsa_2.0.co_2.xml (EDI)

- https://link.springer.com/article/10.1007%2Fs00704-017-2315-2 (KBDI)
